name: Build

on:
  pull_request:
  push:

env:
  PYTHON_VERSION: 3.9

jobs:
  job:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel

    - name: Build
      run: python setup.py sdist bdist_wheel
