name: Check

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  job:
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.8", "3.9", "3.10"]

    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.PYTHON_VERSION }}

    - name: Install ${{ github.event.repository.name }}
      run: |-
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install --upgrade .

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Install pyright
      run: npm install -g pyright

    - name: Check
      run: |-
        pyright ./${{ github.event.repository.name }}
        pyright --verifytypes ${{ github.event.repository.name }} --ignoreexternal
